# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Description')),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'API Keys',
                'verbose_name': 'API Key',
            },
        ),
    ]
