# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 19:59
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20151203_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('UAH', 'Hryvnia'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
    ]
